- CMakeLists.txt
- elf_binary.cc
- elf_binary.h
- print_dynsymtab.cc
- sold.cc
`print_dynsymtab` command parses and prints DT_SYMTAB of a given ELF file.  This command will be very useful when we build VERSYM.
Following is an example of the output.
```
> ./print_dynsymtab tests/test_exe
1: _Z14lib_use_stderrv VER_NDX_LOCAL
2: _Z19lib_base_init_valuev VER_NDX_LOCAL
3: _Z20in_both_lib_and_basev VER_NDX_LOCAL
4: abort GLIBC_2.2.5 (2)
5: _Z14lib_thread_varv VER_NDX_LOCAL
6: _Z19lib_add_42_via_basei VER_NDX_LOCAL
7: _Z25lib_base_thread_var_relocv VER_NDX_LOCAL
8: _Z20lib_thread_var_relocv VER_NDX_LOCAL
9: _Z11lib_base_vfv VER_NDX_LOCAL
10: _Z15lib_base_globalv VER_NDX_LOCAL
11: puts GLIBC_2.2.5 (2)
12: _Z14lib_init_valuev VER_NDX_LOCAL
13: _ITM_deregisterTMCloneTable VER_NDX_LOCAL
14: _Z19lib_base_thread_varv VER_NDX_LOCAL
15: __libc_start_main GLIBC_2.2.5 (2)
16: …
```
> Tool to check DT_SYMTAB

- elf_binary.cc
- sold.cc
My ld.so.conf has paths to 32bit binaries. Like ld-linux, we
should ignore libraries we cannot handle.
> Skip 32bit binaries

- sold.cc
- tests/hello-g++/test.sh
- tests/hello-gcc/test.sh
- tests/just-return-g++/test.sh
- tests/just-return-gcc/test.sh
- tests/simple-lib-g++/test.sh
- tests/simple-lib-gcc/test.sh
If there is no symbols for `gnu_hash_`, we should set `bucket` to 0 in order to show the `gnu_hash_` containing no valid symbols. Without this bugfix, `print_dynsymtab` doesn't works.
> Bugfix for gnu_hash_ containing no symbols 

- CMakeLists.txt
- shdr_builder.cc
- shdr_builder.h
- sold.cc
- tests/hello-g++/test.sh
- tests/hello-gcc/test.sh
- tests/just-return-g++/test.sh
- tests/just-return-gcc/test.sh
- tests/simple-lib-g++/test.sh
- tests/simple-lib-gcc/test.sh
- tests/version-gcc/test.sh
- utils.h
- version_builder.cc
Emit section headers with `--section-headers` option.
After merging the PR, we can see symbols using `readelf`.
```
% readelf -s tests/hello-gcc/hello.out
Symbol table '.dynsym' contains 7 entries:
番号:      値         サイズ タイプ  Bind   Vis      索引名
0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTab
2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.2.5 (2)
3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
4: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
5: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@GLIBC_2.2.5 (2)
6: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND puts@GLIBC_2.2.5 (2)
```
> Emit section headers

- elf_binary.h
- shdr_builder.cc
- shdr_builder.h
- sold.cc
- utils.h
`objdump -d` complains about wrong value of `sh_info` of `.gnu_version.r` section.
ref. [https://docs.oracle.com/cd/E19683-01/816-1386/6m7qcoblj/index.html#chapter6-47976](https://docs.oracle.com/cd/E19683-01/816-1386/6m7qcoblj/index.html#chapter6-47976)
> Fix sh_info to use objdump -d

- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- elf_binary.cc
- elf_binary.h
- print_tls.cc
- sold.cc
- tests/run-all-tests.sh
- tests/tls-bss-g++/main.cc
- tests/tls-bss-g++/test.sh
- tests/tls-bss-gcc/main.c
- tests/tls-bss-gcc/test.sh
- tests/tls-gcc/main.c
- tests/tls-gcc/test.sh
- tests/tls-lib-gcc-without-base/base.c
- tests/tls-lib-gcc-without-base/base.h
- tests/tls-lib-gcc-without-base/lib.c
- tests/tls-lib-gcc-without-base/lib.h
- tests/tls-lib-gcc-without-base/main.c
- tests/tls-lib-gcc-without-base/test.sh
- tests/tls-lib-gcc/base.c
- tests/tls-lib-gcc/base.h
- tests/tls-lib-gcc/lib.c
- tests/tls-lib-gcc/lib.h
- tests/tls-lib-gcc/main.c
- tests/tls-lib-gcc/test.sh
- utils.cc
We should not remap a TLS symbol when it isn't defined.
Tests in `tls-bss-gcc` and `tls-gcc` fail now. However, I think they don't have something to do with this bug. Therefore, I make pass them in the future.
> Do not remap undefined TLS symbol

- elf_binary.cc
We must use only the first Elf_Verdaux entry for each Elf_Verdex entries. (I am surprised that glibc never uses vda_next field.)
Reference
- glibc does not follow a chain of Elf_Verdaux.
https://github.com/bminor/glibc/blob/9538f6b95a3be228edc078ce58258f0574142e0c/elf/dl-version.c#L111
> Use only the first Elf_Verdaux entry

- print_dtrela.cc
- print_dynsymtab.cc
- print_tls.cc
- print_version.cc
- sold.h
`print_dynsymtab` caused runtime errors because we gave an empty map as the filename_to_soname argument. I fixed it in this PR.
Reference
- [96b36ca0 Stop running print_dynsymtab and print_tls because they cause SEGV relating to an empty filename_to_soname. I will fix this bug later.](https://github.com/shinh/sold/pull/37/commits/96b36ca00ea0a559bb5663c31f4b6b9504fa4191)
> Use valid filename_to_soname in print_dynsymtab

- sold.cc
- sold.h
- symtab_builder.cc
- version_builder.cc
- version_builder.h
`vn_file` field of Elf_Verneed should be a filename, not a soname.
Reference1
- Comment in elf.h
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/elf/elf.h#L1062
Reference2
- `find_needed` (auxiliary function to finds needed shared objects) called with `vn_file`
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/elf/dl-version.c#L201
- `find_needed` calls  `_dl_name_match_p`.
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/elf/dl-version.c#L32
- `_dl_name_match_p` matches `name` and `l_name` field in `link_map`.
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/elf/dl-misc.c#L281
- `l_name`  is filename
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad8 …
> Fix vn_file field of Elf_Verneed

- symtab_builder.cc
- symtab_builder.h
- utils.h
When we have no version information for the needed symbol, we must search it without version information.
In this case, we must check whether the VERSYM_HIDDEN(0x8000) bit of versym is set, as you said in https://github.com/shinh/sold/pull/46#discussion_r524304232.
> Search symbols using no version information in the fallback plan

- .github/workflows/build.yml
- sold.cc
- tests/call_once-g++/test.sh
- tests/inheritance-g++/test.sh
- tests/run-all-tests.sh
- tests/static-in-class-g++/lib.cc
- tests/static-in-class-g++/lib.h
- tests/static-in-class-g++/main.cc
- tests/static-in-class-g++/test.sh
- tests/static-in-function-g++/test.sh
- tests/tls-bss-g++/test.sh
- tests/tls-dlopen-gcc/test.sh
- tests/tls-thread-g++/test.sh
- tests/typeid-g++/test.sh
- ubuntu20.04.Dockerfile
- version_builder.cc
- version_builder.h
When there is no Verneed entry, we should not make DT_VERNEED entry. This is because ld-linux.so check vn_version even if DT_VERNEEDNUM is 0. When there is no Verneed entry, I stopped to emit Versyms also. Because emitting Versyms causes a crash in relocation. I don't know the reason.
Although I said there is a bug in the handling of static variables at #51 (comment), it is not true. The crash in tests/static-in-function-g++ was caused by this bug.
Reference
- https://github.com/bminor/glibc/blob/088e9625378f25607acff3daf7a79cbdee497043/elf/dl-version.c#L185
> Suppress emitting unnecessary verneed

- tests/tls-multiple-module-g++/.gitignore
- tests/tls-multiple-module-g++/fuga.cc
- tests/tls-multiple-module-g++/fuga.h
- tests/tls-multiple-module-g++/fugahoge.cc
- tests/tls-multiple-module-g++/hoge.cc
- tests/tls-multiple-module-g++/hoge.h
- tests/tls-multiple-module-g++/main.cc
- tests/tls-multiple-module-g++/test.sh
sold cannot pass this test case now. This is because sold doesn't care about the offsets of TLS variables when there are no R_X86_64_DTPOFF64 relocations.
In this test case, libfuga.so and libhoge.so have their own TLS variables in the anonymous namespace. Therefore, these libraries access their TLS variables only with R_X86_64_DTPMOD64.
> Cannot handle access to TLS variable without R_X86_64_DTPOFF64

- elf_binary.cc
- elf_binary.h
- relocation-list-up.sh
- search-symbol.sh
- sold.cc
- sold.h
- tests/run-all-tests.sh
- tests/tls-multiple-module-g++/fuga.cc
- tests/tls-multiple-module-g++/fugahoge.cc
- tests/tls-multiple-module-g++/hoge.cc
- tests/tls-multiple-module-g++/main.cc
- utils.cc
- utils.h
As I said in https://github.com/shinh/sold/pull/54, sold couldn't handle accesses to TLS variables only with R_X86_64_DTPMOD64. This type of access is called the Local Dynamic model (https://docs.oracle.com/cd/E19253-01/817-1984/6mhm7plbj/index.html ). To handle this model, I changed for sold to rewrite offsets of TLS variables which are embedded in ELF files. 
I didn't handle relocations of R_X86_64_TPOFF64 because they exist only in libpthread.so, libm.so, libc.so, libgomp.so and librt.so and we exclude all of them in the default setting. You can check it with `./relocation-list-up.sh libtorch_cpu.so R_X86_64_TPOFF64`.
> Fix TLS variables of Local Dynamic model

- .github/workflows/build.yml
- CMakeLists.txt
- LICENSE
- README.md
- elf_binary.cc
- elf_binary.h
- print_ehframe.cc
- ubuntu18.04.Dockerfile
- ubuntu20.04.Dockerfile
- utils.cc
- utils.h
The main change of this PR is `ELFBinary::ParseEHFrameHeader` in https://github.com/shinh/sold/pull/55/commits/1c047428b70a98dcc71b32a512905e6b28bf5dbf. It parses exception information following from the `PT_GNU_EH_FRAME` segment not using the information from any sections.
A `PT_GNU_EH_FRAME` segment has some meta-informations on FDE(Frame Description Entry)s and a binary search table. This table has pointers to each FDEs [1]. `ELFBinary::ParseEHFrameHeader` finds FDEs using these pointers. After that, it parses FDEs following this format [2].
`print_ehframe` is a CLI of `ELFBinary::ParseEHFrameHeader`. I have checked that `print_ehframe` works well for all depending shared objects of `libtorch.so`.
References
[1]: https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB/ehframehdr.html …
> Parse EH frame header

- sold.cc
- sold.h
We could not call  `DecideOffset` before building TLS because it depended on `Sold::tls_`. When it comes to appending `PT_GNU_FH_FRAME` or `PT_LOAD` after TLS template image, this restriction complicates the code.
So I make `Sold::TLSMemSize` and `Sold::EHFrameSize` so that we can call `DecideOffset` before building `Sold::tls_` and `Sold::ehframe_builder_`.
> Refactor DecideOffset

- sold.cc
- sold_main.cc
R_X86_64_TPOFF64 is a relocation type for an offset in the initial TLS block. We can support it just the same as R_X86_64_DTPOFF64.
> Support R_X86_64_TPOFF64

- sold.cc
- sold.h
According to https://refspecs.linuxbase.org/elf/gabi4+/ch5.dynamic.html#init_fini, we must initialize shared objects in the topological order. To achieve this, I make the order of `link_binaries_` topological.
> Order of link_binaries_

- sold.cc
- sold.h
- sold_main.cc
- I had forgot to call `AlignNext()` in `EHFrameOffset()`.
- I had made mistake the order between `BuildEHFrameHeader()` and `BuildLoads()`. Because `BuildEHFrameHeader()` depends on `BuildLoads()` via `EHFrameOffset()` and `TLSOffset()`, we must call it after  `BuildLoads()`.
I made `--check-output` option because we can prevent such bugs if we check the output using sold itself.
> Fix a bug on the offset of eh_frame

- elf_binary.cc
- sold.h
- tests/call_once-g++/test.sh
- tests/dynamic_cast-g++/test.sh
- tests/exception-g++/test.sh
- tests/hello-g++/test.sh
- tests/hello-gcc/test.sh
- tests/inheritance-g++/test.sh
- tests/just-return-g++/test.sh
- tests/just-return-gcc/test.sh
- tests/run-all-tests.sh
- tests/simple-lib-g++/test.sh
- tests/simple-lib-gcc/test.sh
- tests/static-in-class-g++/test.sh
- tests/static-in-function-g++/test.sh
- tests/tls-dlopen-gcc/test.sh
- tests/tls-lib-gcc-without-base/test.sh
- tests/tls-lib-gcc/test.sh
- tests/tls-multiple-lib-gcc/test.sh
- tests/tls-multiple-module-g++/test.sh
- tests/tls-thread-g++/test.sh
- tests/typeid-g++/test.sh
- tests/version-gcc/test.sh
- utils.h
After I changed to use the `--check-output` option in all tests, I found some TLS related tests such as `tls-dlopen-gcc` failed. I found all of them have TLS variables without initial values and don't have TLS variables with initial values.
These crashes are because of the overlap of the TLS template image and GNU_EH_FRAME as you can see in the following. And the reason of the overlap is that `EHFrameOffset()` and `TLSOffset()` returned the same value  when `TLSFileSize()` is 0. I fixed it in https://github.com/shinh/sold/commit/0eb61cbabc88c993e1b7e9028a274e7e99a28d1a by emitting a dummy TLS image in order to make the size non-zero always.
```
> readelf -l lib.so.soldout
Elf file type is DYN (Shared object file)
Entry point 0x10001080
There are 12 program headers, starting at offset 64 …
```
> Fix bugs in AddrFromOffset and OffsetFromAddr (formarly Overlap between TLS template image and GNU_EH_FRAME)

- symtab_builder.cc
- tests/run-all-tests.sh
- tests/stb_gnu_unique_tls/.gitignore
- tests/stb_gnu_unique_tls/main.cc
- tests/stb_gnu_unique_tls/test.sh
- tests/stb_gnu_unique_tls/unique.cc
I found that `stb_gnu_unique_tls` failed because of a symbol lookup error. This because the index of `_ZZ9inline_fnvE1c` is smaller than `gnu_hash_.symndx` and the loader looks only at symbols after `gnu_hash_.symndx`.
I think there is two way to fix this bug.
- Fix `gnu_hash_.symndx`
- Fix the order of symbols
I decided to take the first one because it is easy to implement although it imposes some overhead on the loader.
```
> readelf --dyn-syms libunique.so.soldout 
Symbol table '.dynsym' contains 10 entries:
Num:    Value          Size Type    Bind   Vis      Ndx Name
0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTab
2: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
3: …
```
> Workaround for symbol lookup error

- elf_binary.cc
- listup_duplicated_syms.py
- sold_main.cc
- symtab_builder.cc
- tests/call_once-g++/.gitignore
- tests/call_once-g++/fuga.cc
- tests/call_once-g++/hoge.cc
- tests/call_once-g++/lib.h
- tests/call_once-g++/main.cc
- tests/call_once-g++/test.sh
After I change call_once-g++ test in https://github.com/shinh/sold/commit/0c10640b5db800bc2aaf631d3aaeab4cdcb87711, I found this test fails. The following code snippet is a part of the symbol table of libfuga.so at https://github.com/shinh/sold/commit/0c10640b5db800bc2aaf631d3aaeab4cdcb87711. As you can see, _ZSt15__once_callable appears twice. Furthermore, _ZSt15__once_callable appears as a defined symbol.
However, _ZSt15__once_callable must not be defined in libfuga.so because it is defined in libstdc++.so which is in EXCLUDE_SHARED_OBJECTS.
```
> readelf --dyn-syms --wide libfuga.so | grep __once_call 
19: 0000000000000000     0 TLS     GLOBAL DEFAULT  UND _ZSt15__once_callable@GLIBCXX_3.4.11 (8)
21: 0000000000000000     0 TLS     GLOBAL DEFAULT  UND _ZSt11__once_call@GLIBCXX_3.4.11 …
```
> Duplicated symbols cause a crash

- elf_binary.cc
- elf_binary.h
- sold.cc
- tests/run-all-tests.sh
- tests/tls-bss-g++/main.cc
- tests/tls-bss-gcc/main.c
Because we bundle up TLS initialization images of multiple shared objects, we must remap addresses of relocations in them.  However, we made mistake on the sizes of TLS initialization images. While we used `p_memsz` as the size of TLS initialization images, we should use `p_filesz`. (https://github.com/shinh/sold/commit/634fb990b697ffa5df8d625d75b005e9f6bdb2d2 and https://github.com/shinh/sold/commit/05fb3fa21a7e7af45da772fd0a77e83452954ec7)
In addition to it, I rewrite `InTLS`, `InTLSData`, and `InTLSBSS` not to compare a pointer and an integer directly.
> Fix a bug of remapping address in TLS initialization images

- print_dynsymtab.cc
- sold.cc
- sold.h
- sold_main.cc
I found some `.fini_array` causes SEGV for an unknown reason. For example, `.fini_array` of `libtorch_cpu.so` failed when it called after one of `libtorch_cuda.so`.
As a temporal solution, I made the `--exclude-from-fini` option. It excludes a given SO file from `.fini_array`. You can use it like the following.
```
sold -i libtorch_test.so.original -o libtorch_test.so.soldout --section-headers --exclude-from-fini libtorch_cpu.so
```
> Exclude fini option

- sold.h
I remove this assertion because some libraries such as libicudata.so have no relocations.
(I notice this when I tried to link clang.)
> Remove CHECK(bin->rel()) assertion

- elf_binary.cc
Because PT_TLS section also takes up memory space, we must consider when converting an address to an offset and vice versa.
> PT_TLS section also takes up memory space

- elf_binary.cc
- sold.cc
- tests/call_once-g++-aarch64/test.sh
- tests/run-all-tests.sh
This PR makes sold to support a `R_AARCH64_TLSDESC` relocation.
When `ld-linux` handles a `R_AARCH64_TLSDESC` relocation, There are two main ways.
When the relocation related to a non-valid symbol ([glibc/dl-machine.h L307](https://github.com/bminor/glibc/blob/595c22ecd8e87a27fd19270ed30fdbae9ad25426/sysdeps/aarch64/dl-machine.h#L307)), `ld-linux` uses only `r_addend` as the offset in a TLS block. In this case, we must rewrite `r_addend` appropriately because we remap TLS images ([sold.cc L773](https://github.com/akawashiro/sold/blob/5f2d4010cdf21e47e9dd6c512efb2e80888e7ee0/sold.cc#L773)).
When the relocation related to a valid symbol ([glibc/dl-machine.h L312](https://github.com/bminor/glibc/blob/595c22ecd8e87a27fd19270ed30fdbae9ad25426/sysdeps/aarch64/dl-machine.h#L312)), `ld-linux` …
> Aarch64 TLSDESC

- elf_binary.cc
- elf_binary.h
- libtorch_test/CMakeLists.txt
- sold.cc
- sold.h
This PR fixes bugs of `.init_array` and `.fini_array`.
We have emitted relocations of `R_X64_64_RELATIVE` or `R_AARCH64_RELATIVE` for all entries in arrays. But it is not appropriate when the original shared objects use relocations other than `R_*_RELATIVE`. For example, `liblapack.so.3` uses `R_AARCH64_ABS64` as discussed in Slack.
I stopped emitting `R_*_RELATIVE` relocations unconditionally and re-use relocations of the original shared objects to resolve this bug. I implemented this just as same as TLS ones. `Sold` class records mappings from `Elf_binary*` to new offsets of arrays in https://github.com/shinh/sold/commit/44cd940d7148179929b792d3a0bbf2abea3b1598 and remap relocations using the mappings in https://github.com/shinh/sold/commit/e51d6a7c292045ae0615132ada9910ea12189535.
In …
> Fix arrays
